---
# # 服务器前置任务(ubuntu使用)
- name: Preinstall-BT
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
   - name: Install Python
     raw: sudo apt update && sudo apt-get -y install python
     ignore_errors: True


# # 核心任务

- name: BT
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  roles:  
    - { role: bt, tags: "bt"}
    - { role: end, tags: "end"}