---
# 核心任务
- name: main
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  vars_prompt:
    - name: 'language_choose'
      prompt: "Choose BT language \n
      1: Chinese (default)\n
      2: English\n"
      private: no
      default: 1

  vars:
     languagever:
      '1': 'zh'
      '2': 'en'

     language_ver: "{{languagever[language_choose]}}"

  roles:  
    - { role: role_common, tags: "role_common"}
    - { role: role_cloud, tags: "role_cloud"}
    - { role: bt, tags: "bt"}
    - { role: role_preend, tags: "role_preend"}
    - { role: role_end, tags: "role_end"}
